version: '3'
services:
  postgresql:
    image: postgres:11.7-alpine
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: i_have_i_need_development
      POSTGRES_USER: dev_local_user
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "4000:4000"
      - "35729:35729"
    environment:
      - HOSTNAME=localhost:3000
      - DOCKERIZED=true
    depends_on:
      - postgresql

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - 5900:5900

  selenium_firefox:
    image: selenium/standalone-firefox-debug
    logging:
      driver: none
    ports:
      - 5900:5900
