version: '3'
services:
  postgresql:
    image: postgres:11.7-alpine
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: i_have_i_need_development
      POSTGRES_USER: dev_local_user
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pif && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
