FROM ruby:2.6.0

ENV BUNDLER_VERSION=2.1.4

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client yarn
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
&& apt-get install -y nodejs
RUN gem install bundler -v 2.1.4
ENV RAILS_ENV development
ENV DATABASE_HOST postgresql
WORKDIR /app
COPY Gemfile Gemfile.lock /app/
COPY package.json yarn.lock /app/

RUN bundle
RUN yarn install --check-files
COPY . /app
RUN rake camden_style_guide:webpacker:compile
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
