default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
    database: i_have_i_need_development
    username: dev_local_user
    password: password
  audit_logs_db:
    <<: *default
    host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
    database: audit_logs_db_development
    username: dev_local_user
    password: password
    migrations_paths: db/audit_logs_db_migrate

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  database: i_have_i_need_test
  username: test_local_user
  password: password

production:
  primary:
    <<: *default
    database: i_have_i_need_production
    username: i_have_i_need
    password: <%= ENV['I_HAVE_I_NEED_DATABASE_PASSWORD'] %>
  audit_logs_db:
    <<: *default
    database_url: <%= JSON.parse(ENV['VCAP_SERVICES'])["postgres"][1]["credentials"]["uri"] %>
    # username: i_have_i_need
    # password: <%= ENV['I_HAVE_I_NEED_DATABASE_PASSWORD'] %>
    migrations_paths: db/audit_logs_db_migrate
