name: Ruby Cucumber Tests
# As opposed to the ci env used before on the Ruby action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11.7-alpine
        env:
          POSTGRES_USER: test_local_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: i_have_i_need_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.8
      uses: ruby/setup-ruby@v1
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems1-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems1-
    - name: Install gems
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Setup database
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails db:drop
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails db:seed
    - name: Compile assets
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails assets:precompile
    - name: Run cucumber tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec cucumber --fail-fast
